Homepage Lastest post- Update Certification section
cetav-ddw/conversABLE pull request #5
Opened 2017-05-28 01:04 UTC by majosm96

Cambios
-Pase el archivo de buttons que estaba en modules a patterns
-Nueva sección home LastestPost (Creo que falta mas diseño pero la estructura esta lista)
-Revise la página de get certifited y tenía varios errores siguiendo el diseño. Quedo lista. 
-Solo tengo un problema en esa sección dando margin a un anchor ya intente varias cosas desde ayer, mañana lo vuelvo a revisar

2017-05-28 02:46 UTC, jleiva requested changes

2017-05-28 02:46 UTC, jleiva commented on es/certifiquese.html
> +         <section class="l-group section-wrap certification-mainWrap">
no usamos camelcase en los nombres de clases.

2017-05-28 02:46 UTC, jleiva commented on es/certifiquese.html
> +              <p>El resultado: mayor auto-compasión, autenticidad y empatía; mejor  comunicación con  nosotros mismos y con los demás; más armonía en nuestras  relaciones.</p>
porque dos veces el mismo texto de "El resultado....."?

2017-05-28 02:46 UTC, jleiva commented on index.html
> +    </footer> -->
ojo aca esos caracteres -->

2017-05-28 02:46 UTC, jleiva commented on sass/partials/_variables.scss
> +$background-gray: #F3F2F2;
para este tipo de colores, el nombre de la variable no debe ser tan especifico, porque si despues lo queremos usar para un texto o otro elemento en el que no se va a usar como background, se vuelve confuso

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	// text-transform: uppercase;
remover los comentarios.

Revisar contra el diseño https://drive.google.com/open?id=0B_g0dRelBE-7NEhTT25WQXR1QjA

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +		text-align: justify;
no justificamos textos

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	a, h3, h4, h5, p {
una propiedad por linea cuando se agrupa.

Lo que se esta siguiendo es BEM, como metodologia para nombrar, entonces es mejor ponerle una clase a cada elemento,; pero, pero, para efectos del prototipo se puede quedar asi; cuando nos movamos a al tema de Drupal, ya hay que hacerlo bien

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	margin: 25px 0 100px 0;
un espacio despues de la propiedad y antes de las reglas anidadas.
usa shorthand en este margin

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +		margin: 30px 0 30px 0;
no justificar, usar shorthand y un selector por linea

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +// 	padding: 25px 0 100px 0;
sino se esta usando no tiene porque estar aca

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_lastest-posts.scss
> +.lastest-post_wrap {
wooooaaaaa, no metan flexbox. Para incluirlo debemos estar seguros del soporte en todos los browsers, y de tener un fallback.

Yo lo meti en la parte del equipo como una prueba.

2017-05-28 02:46 UTC, jleiva commented on index.html
> ++<!DOCTYPE html>
tenes un mal merge, o algo paso, tenes un caracter de ++ en la linea 1 de index.html

2017-05-28 02:46 UTC, jleiva commented on index.html
> +        <section class="l-group section-wrap lastest-posts">
el section, contiene las secciones de la pagina, las clases deberian de ser genericas, **lastest-posts** no debe cambiar el ancho de la seccion, quitar esa clase.

El width de 90% se lo podes poner al wrapper de los post

2017-05-28 02:46 UTC, jleiva commented on index.html
> +            <div class="lastest-post bg-gray primary-post">
si todos los post tienen el mismo background, la clase bg-gray es innecesaria. Ese color de fondo puede ser parte de las declaraciones de lastest-post

2017-05-28 02:46 UTC, jleiva commented on index.html
> +            <div class="lastest-post bg-gray secondary-post">
te falto el anchor, cual elemento va a ser cliqueable para poder ir al detalle del post?

2017-05-28 02:46 UTC, jleiva commented on getcertified.html
>        <main role="main">
este file debe tener el mismo contenido que el de español, despues cambiamos los textos, si es que salen traducibles. pero para efectos del prototipo, no dummy text

2017-05-28 02:46 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	}
Ojo con lo del margin: 0 auto. estas sobre escribiendo el margn-bottom de esos elementos, entonces los parrafos se ven todos pegados. Ademas, si el contenedor es que esta centrado, esta declaracion es innecesaria

![image](https://cloud.githubusercontent.com/assets/598867/26525656/7e0c092a-431b-11e7-833f-a0a4f56d0f80.png)

2017-05-28 02:46 UTC, jleiva commented on es/certifiquese.html
>              <h4>Mayo-Julio 2017</h4>
esto es lo mismo que hablamos el Viernes con Maria, no tiene sentido tener dos h3, o dos h4 seguidos.

Las clases de los titulos deberian de poder ser reutilizadas, cambiar la clase para que sea mas generica. Si la necesitas especifica, entonces las clases de tu module deberian de tener el mismo patron. Por ejemplo, todo iniciar con certification-

2017-05-28 02:46 UTC, jleiva commented on es/certifiquese.html
> +            <a class="btn-fill btn-certification">Inscribirme</a>
no a este tipo de clases para botones, me refiero a **btn-certification** El viernes hable con Juan y Maria para que estandaricen los estilos de los botones, y que tengamos clases listas para usar, asi como el contexto en el que se usa cada boton.

Por el momento, dejalo solo con btn-fill

2017-05-28 02:48 UTC, jleiva commented
Ojo, estas combinando dos tareas diferentes en un mismo branch, deberias haber enviado un pull request solo con lo de latest post, y otro con la parte de certificacion. Por el momento, aplica los cambios solicitados en este branch, pero para futuras tareas, no mezclar para evitar atrasos

2017-05-29 04:40 UTC, jleiva requested changes

2017-05-29 04:40 UTC, jleiva commented on sass/partials/patterns/_buttons.scss
>  .btn-certification {
no es necesario incluir un boton tan especifico, remover esta regla. Juan y Maria van a incluir las variantes de botones

2017-05-29 04:40 UTC, jleiva commented on sass/partials/modules/_lastest-posts.scss
> +  background-color: $main-gray;
indentacion

2017-05-29 04:40 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +		margin-bottom: none;
No justificar textos.
La propiedad margin-bottom, no acepta ese valor de none.

Y en los comentarios anteriores te indique cambiar lo que esta en las lineas 10 a 14.  Podes ponerle una clase a cada elemento y darle el estilo que necesitas

2017-05-29 04:40 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	margin: 50px 0 50px 0;
shorthand

2017-05-29 04:40 UTC, jleiva commented on es/certifiquese.html
> +            <a class="btn-fill btn-certification">Inscribirme</a>
quitar la clase **btn-certification**

2017-05-29 04:40 UTC, jleiva commented on es/index.html
>          </section>
este archivo no tiene las mismas clases que la version en ingles

2017-05-29 04:40 UTC, jleiva commented on sass/partials/_variables.scss
> +$main-gray: #F3F2F2;
solo $gray

2017-06-02 01:33 UTC, jleiva requested changes
Este pull request esta actualizado con lo ultimo que esta en el repo?

2017-06-02 01:33 UTC, jleiva commented on getcertified.html
> +            <h3 class="certification-h">Programa de integración</h3>
Creo que te lo dije en otro review, usamos BEM para nombrar clases, seguir el estandar por favor

2017-06-02 01:33 UTC, jleiva commented on sass/partials/modules/_lastest-posts.scss
> +  background-color: $main-gray;
indentacion

2017-06-02 01:33 UTC, jleiva commented on sass/partials/modules/_lastest-posts.scss
> +  span {
nueva linea entre bloque de reglas

2017-06-02 01:33 UTC, jleiva commented on sass/partials/modules/_lastest-posts.scss
> +  width: 90%;
hay que ser consistente con la identacion, creo que estamos a 4 espacios, este parece a 2

2017-06-02 01:33 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +	p {
una nueva linea antes de los bloques anidados

2017-06-04 18:10 UTC, jleiva requested changes

2017-06-04 18:10 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +.certification__h3--resize {
porque resize? y no tiene que ser h3, pueder ser solo .certification__title, o .certification__subtitle, dependiendo de lo que sea. porque separar dos clases, .certification-h y .certification__h3--resize, y porque no dejar solo -h y que esa tenga todas las declaraciones?

2017-06-04 18:10 UTC, jleiva commented on sass/partials/modules/_certification-section.scss
> +.certification__text--bold {
si la clase es tan especifica como para indicar que va a ser text-bold, es confuso que tenga un margin, o alguna otra propiedad que no sea font-weight. Yo haria lo siguiente:

* como son detalles importantes de la certificacion, usaria un `<ul>`
* al `<ul>` le pondria una clase tipo certification__details
* le dejo los bullets, y tendria algo como

```
.certification__details {
   font-weight: $font-family-base-bold-weight;
}
```

2017-06-04 20:29 UTC, majosm96 commented on sass/partials/modules/_certification-section.scss
> +.certification__h3--resize {
Listo la clase heading actualizada, se me fue eso obviamente podrían estar en una misma clase la próxima reviso mejor.

2017-06-04 20:32 UTC, majosm96 commented on sass/partials/modules/_certification-section.scss
> +.certification__text--bold {
No se si lo mejor sea un `ul` , había agregado el margin 0 porque como los `p` tienen un margin en el base que no estaba necesitando en esa sección.
Ya están en `ul,` solo con una clase y deje los bullets. Pero herendan el font del html que es un poco más pequeño. En la misma clase cambie el font size, supongo que esta bien porque ya solo son propiedades del font. Ud que opina?

Esa clase también la estaba utilizando para la descripción que esta debajo del subtitulo (Fecha & cupo), estos los necesito sin margin, no creo que una lista funcione muy bien ahí no?.  Hago otra clase con las mismas propiedades, no me suena muy bien.
Otra solución es que repita la clase de certification__details (tendería que cambiarle el nombre) y en el block de certification al p:nth-child(1) le ponga margin-bottom: 0;. Como lo hize en el block de certification-descrip pero ya lo intente no se porque no me esta funcionando.

2017-06-06 16:53 UTC, merged